### ISSUE TITLE
"The page was updated successfully" dialogue cannot be closed/dismissed

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/pwakit#17]
On saving edits to a page, this banner appears but the "X" doesn't work to close it.
![image](https://user-images.githubusercontent.com/10574730/64115269-0b936980-cd87-11e9-92cd-7f610a2bb75b.png)

**Comment by joeaudette** [comment]
When I run the solution locally it works as intended. Instead of a full width notification, it is just in the top right corner and it closes automatically after a few seconds.

Can you check for script errors or 404 for any scripts on your end?
